### ISSUE TITLE
[BUG] Corrigir erro na função de conversão das potências

### ISSUE THREAD

**Issue by jobson-almeida** [jobson-almeida/u3c3o12t-converter#18]
Favor checar o código abaixo sobre os cálculos de conversão de potência. 

https://github.com/jobson-almeida/u3c3o12t-converter/blob/5fe569c863ef826712138407e1e071000e4d755c/main.c#L489-L502

As imagens exibem o teste realizado com a opção 3 e uma referência para comparação. Favor revisar as demais opções.

![potencia](https://github.com/user-attachments/assets/4c895685-6f3c-48f9-b32d-9a5b854ef5e7)

![potencias 1](https://github.com/user-attachments/assets/759c7fc2-310f-47c1-8b77-ddc378fa3116)

**Comment by zSukita** [comment]
Corrigido !
