### ISSUE TITLE
[BUG] Corrigir entrada e tratamento de dados

### ISSUE THREAD

**Issue by jobson-almeida** [jobson-almeida/u3c3o12t-converter#21]
Observei algumas falhas ao tentar inserir caracteres inválidos. Abaixo  algumas imagens que retratam alguns desses sintomas.

Executa o cálculo e chama o submenu duas vezes

![potencia 1](https://github.com/user-attachments/assets/8caebda1-8049-40d8-aa20-380f9c5b936b)

Aceita valor inválido, calcula o número, descarta a letra e chama o submenu por duas vezes

![potencia 2](https://github.com/user-attachments/assets/b9bce74e-6760-4fc9-a5b4-0bcf83e661b1)

Casos semelhantes ocorrem nas demais imagens

![comp1](https://github.com/user-attachments/assets/b7850357-c561-4f36-8a2b-01c9b858d1bc)

![comp2](https://github.com/user-attachments/assets/1dd342d7-ebb5-4517-983a-4bbac10541d7)

![comp3](https://github.com/user-attachments/assets/a6d66da8-8a9c-484e-bc45-b233cfab1f8b)

![massa](https://github.com/user-attachments/assets/5f34c0cb-1603-4cc5-995b-c6a0ef3b8cef)

![massa2](https://github.com/user-attachments/assets/abd495dd-c638-44a5-bb5f-b10ba387a0dd)

![massa3](https://github.com/user-attachments/assets/1e3cc50c-6f26-4de7-87a3-9a6476555fb2)

![potencia 1](https://github.com/user-attachments/assets/5f124142-7b4a-43a6-8a23-2b9977e1d137)

![temp1](https://github.com/user-attachments/assets/1e4951fd-778d-4ae3-a6dc-5fed1ece56be)

![temp2](https://github.com/user-attachments/assets/9966cfb2-4225-40b7-83b8-d6d6280eaf62)

![temp3](https://github.com/user-attachments/assets/394d1c33-f020-4742-b959-fa6285d69e15)

Diante disse, as features abaixo precisam ser corrigidas:
- [x] Menu principal
- [x] Comprimento
- [x] Massa
- [x] Temperatura
- [x] Potência

**Comment by jobson-almeida** [comment]
correção aplicada no menu principal. A opção digitada pelo usuário agora é validada antes de qualquer outra ação. A validação impede que outros caracteres, além do inteiro, seja aceito pela aplicação.

**Comment by camillerodriguees** [comment]
Erro na feature COMPRIMENTO foi corrigido, aguardando merge.
