### ISSUE TITLE
Adicionar Biblioteca

### ISSUE THREAD

**Issue by zSukita** [jobson-almeida/u3c3o12t-converter#4]
adicionar biblioteca locale.h, e adicionar no código   setlocale(LC_ALL, "pt_BR.UTF-8"); ou setlocale(LC_ALL, "Portuguese");

**Comment by jobson-almeida** [comment]
Olá Lucas
,
Creio que esteja falando sobre o problema que teve com a acentuação no menu, relacionado a imagem postada no grupo. Se é esse o caso, sua sugestão foi aplicada ao projeto. Valeu pela contribuição
